# Generated by Django 5.1.7 on 2025-03-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarbonIntensityStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                ("min_intensity", models.IntegerField()),
                ("max_intensity", models.IntegerField()),
                ("average_intensity", models.FloatField()),
                ("block_hours", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Carbon Intensity Statistics",
                "ordering": ["-from_datetime"],
                "unique_together": {("from_datetime", "to_datetime", "block_hours")},
            },
        ),
        migrations.CreateModel(
            name="GenerationMix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                ("fuel_mix", models.JSONField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Generation Mixes",
                "ordering": ["-from_datetime"],
                "unique_together": {("from_datetime", "to_datetime")},
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "postcode_prefix",
                    models.CharField(blank=True, max_length=4, null=True, unique=True),
                ),
                ("short_name", models.CharField(max_length=50, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["postcode_prefix"],
                        name="carbon_inte_postcod_13fd36_idx",
                    ),
                    models.Index(
                        fields=["short_name"], name="carbon_inte_short_n_a71521_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarbonIntensity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_datetime", models.DateTimeField()),
                ("to_datetime", models.DateTimeField()),
                ("actual", models.IntegerField(blank=True, null=True)),
                ("forecast", models.IntegerField(blank=True, null=True)),
                (
                    "index",
                    models.CharField(
                        choices=[
                            ("very low", "Very Low"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("very high", "Very High"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "postcode_prefix",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intensity_data",
                        to="carbon_intensity.region",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_datetime"],
                "indexes": [
                    models.Index(
                        fields=["from_datetime", "to_datetime"],
                        name="carbon_inte_from_da_aa64b3_idx",
                    ),
                    models.Index(
                        fields=["postcode_prefix"],
                        name="carbon_inte_postcod_70a67c_idx",
                    ),
                    models.Index(fields=["index"], name="carbon_inte_index_98393a_idx"),
                ],
                "unique_together": {
                    ("from_datetime", "to_datetime", "region", "postcode_prefix")
                },
            },
        ),
    ]
