"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DEVELOPMENT = os.environ.get("APP_DEVELOPMENT", "false").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
if DEVELOPMENT:
    SECRET_KEY = "django-insecure-jd)wmqtrm3o(^pech(5&=ofdd8@5b)j-t=+gm9zhjz39b1j*5n"
else:
    SECRET_KEY = os.environ["APP_SECRET"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = DEVELOPMENT and os.environ.get("APP_DEBUG", "true").lower() != "false"

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SECURE = not DEVELOPMENT

if DEVELOPMENT:
    ALLOWED_HOSTS = ["*"]
    CSRF_TRUSTED_ORIGINS = ["http://*"]
    CORS_ALLOW_ALL_ORIGINS = True
else:
    ALLOWED_HOSTS = ["energy.lookingforgrowth.uk", "energy.lfgdata.uk"]
    CSRF_TRUSTED_ORIGINS = ["https://energy.lookingforgrowth.uk", "https://energy.lfgdata.uk"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
    "apps.core",
    "apps.carbon_intensity",
    "apps.national_grid_eso",
    "apps.elexon",
    "apps.octopus",
    "apps.core.utils",
]

MIDDLEWARE = [
    "api.middleware.HealthCheckMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEVELOPMENT:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.environ["APP_DATABASE_HOST"],
            "PORT": os.environ.get("APP_DATABASE_PORT", ""),
            "NAME": os.environ["APP_DATABASE_NAME"],
            "USER": os.environ["APP_DATABASE_USER"],
            "PASSWORD": os.environ["APP_DATABASE_PASSWORD"],
            "CONN_MAX_AGE": 120,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# settings.py additions
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
# CELERY_TIMEZONE = 'UTC'
# CELERY_BEAT_SCHEDULE = {
#     'update-intensity-every-30min': {
#         'task': 'carbon_intensity.tasks.update_intensity_data',
#         'schedule': 1800,
#     },
#     'update-generation-mix-hourly': {
#         'task': 'carbon_intensity.tasks.update_generation_mix',
#         'schedule': 3600,
#     },
# }

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://localhost:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "100/hour", "user": "1000/hour"},
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
}


SWAGGER_SETTINGS = {"DEFAULT_INFO": "api.urls.api_info"}


# API KEYS

BMRS_API_KEY = os.environ.get("BMRS_API_KEY", None)
