dummy_region_data = {
    "data": [
        {
            "from": "2025-03-25T15:00Z",
            "regions": [
                {
                    "dnoregion": "Scottish Hydro Electric Power " "Distribution",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0},
                        {"fuel": "gas", "perc": 0},
                        {"fuel": "nuclear", "perc": 0},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 0},
                        {"fuel": "wind", "perc": 100},
                    ],
                    "intensity": {"forecast": 0, "index": "very low"},
                    "regionid": 1,
                    "shortname": "North Scotland",
                },
                {
                    "dnoregion": "SP Distribution",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 2},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0},
                        {"fuel": "gas", "perc": 0},
                        {"fuel": "nuclear", "perc": 20.3},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 7.9},
                        {"fuel": "wind", "perc": 69.8},
                    ],
                    "intensity": {"forecast": 2, "index": "very low"},
                    "regionid": 2,
                    "shortname": "South Scotland",
                },
                {
                    "dnoregion": "Electricity North West",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 2},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 5.4},
                        {"fuel": "gas", "perc": 13.3},
                        {"fuel": "nuclear", "perc": 35.3},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 5.5},
                        {"fuel": "wind", "perc": 38.5},
                    ],
                    "intensity": {"forecast": 55, "index": "low"},
                    "regionid": 3,
                    "shortname": "North West England",
                },
                {
                    "dnoregion": "NPG North East",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 14.4},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 43.5},
                        {"fuel": "gas", "perc": 0},
                        {"fuel": "nuclear", "perc": 28.3},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 8.6},
                        {"fuel": "wind", "perc": 5.1},
                    ],
                    "intensity": {"forecast": 19, "index": "very low"},
                    "regionid": 4,
                    "shortname": "North East England",
                },
                {
                    "dnoregion": "NPG Yorkshire",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 20.7},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 5.1},
                        {"fuel": "gas", "perc": 42.3},
                        {"fuel": "nuclear", "perc": 3.1},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 5.7},
                        {"fuel": "wind", "perc": 23.2},
                    ],
                    "intensity": {"forecast": 192, "index": "high"},
                    "regionid": 5,
                    "shortname": "Yorkshire",
                },
                {
                    "dnoregion": "SP Manweb",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0.8},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 1.3},
                        {"fuel": "gas", "perc": 31.3},
                        {"fuel": "nuclear", "perc": 11.7},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 16.4},
                        {"fuel": "wind", "perc": 38.6},
                    ],
                    "intensity": {"forecast": 124, "index": "moderate"},
                    "regionid": 6,
                    "shortname": "North Wales & Merseyside",
                },
                {
                    "dnoregion": "WPD South Wales",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0},
                        {"fuel": "gas", "perc": 81.4},
                        {"fuel": "nuclear", "perc": 0},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 14.9},
                        {"fuel": "wind", "perc": 3.7},
                    ],
                    "intensity": {"forecast": 321, "index": "very high"},
                    "regionid": 7,
                    "shortname": "South Wales",
                },
                {
                    "dnoregion": "WPD West Midlands",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 1.4},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 2.2},
                        {"fuel": "gas", "perc": 49.2},
                        {"fuel": "nuclear", "perc": 11.8},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 12.9},
                        {"fuel": "wind", "perc": 22.6},
                    ],
                    "intensity": {"forecast": 196, "index": "high"},
                    "regionid": 8,
                    "shortname": "West Midlands",
                },
                {
                    "dnoregion": "WPD East Midlands",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 3.7},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0.9},
                        {"fuel": "gas", "perc": 67.9},
                        {"fuel": "nuclear", "perc": 0.6},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 9.3},
                        {"fuel": "wind", "perc": 17.7},
                    ],
                    "intensity": {"forecast": 272, "index": "very high"},
                    "regionid": 9,
                    "shortname": "East Midlands",
                },
                {
                    "dnoregion": "UKPN East",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0.5},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 6},
                        {"fuel": "gas", "perc": 36.2},
                        {"fuel": "nuclear", "perc": 26.6},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 10.5},
                        {"fuel": "wind", "perc": 20.2},
                    ],
                    "intensity": {"forecast": 163, "index": "moderate"},
                    "regionid": 10,
                    "shortname": "East England",
                },
                {
                    "dnoregion": "WPD South West",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0.1},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 4.5},
                        {"fuel": "gas", "perc": 34},
                        {"fuel": "nuclear", "perc": 0},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 59.6},
                        {"fuel": "wind", "perc": 1.8},
                    ],
                    "intensity": {"forecast": 136, "index": "moderate"},
                    "regionid": 11,
                    "shortname": "South West England",
                },
                {
                    "dnoregion": "SSE South",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0.6},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 32.6},
                        {"fuel": "gas", "perc": 43.2},
                        {"fuel": "nuclear", "perc": 0.3},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 19.3},
                        {"fuel": "wind", "perc": 3.9},
                    ],
                    "intensity": {"forecast": 188, "index": "high"},
                    "regionid": 12,
                    "shortname": "South England",
                },
                {
                    "dnoregion": "UKPN London",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0.2},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 32.6},
                        {"fuel": "gas", "perc": 39.7},
                        {"fuel": "nuclear", "perc": 7.3},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0.2},
                        {"fuel": "solar", "perc": 8.8},
                        {"fuel": "wind", "perc": 11.2},
                    ],
                    "intensity": {"forecast": 180, "index": "high"},
                    "regionid": 13,
                    "shortname": "London",
                },
                {
                    "dnoregion": "UKPN South East",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 46.3},
                        {"fuel": "gas", "perc": 40.2},
                        {"fuel": "nuclear", "perc": 0},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0.3},
                        {"fuel": "solar", "perc": 5.4},
                        {"fuel": "wind", "perc": 7.8},
                    ],
                    "intensity": {"forecast": 184, "index": "high"},
                    "regionid": 14,
                    "shortname": "South East England",
                },
                {
                    "dnoregion": "England",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 3.6},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 16.5},
                        {"fuel": "gas", "perc": 38.5},
                        {"fuel": "nuclear", "perc": 11.4},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 12.7},
                        {"fuel": "wind", "perc": 17.3},
                    ],
                    "intensity": {"forecast": 168, "index": "moderate"},
                    "regionid": 15,
                    "shortname": "England",
                },
                {
                    "dnoregion": "Scotland",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 1.8},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0},
                        {"fuel": "gas", "perc": 3.6},
                        {"fuel": "nuclear", "perc": 15.5},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 6.8},
                        {"fuel": "wind", "perc": 72.2},
                    ],
                    "intensity": {"forecast": 16, "index": "very low"},
                    "regionid": 16,
                    "shortname": "Scotland",
                },
                {
                    "dnoregion": "Wales",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 0},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 0},
                        {"fuel": "gas", "perc": 72},
                        {"fuel": "nuclear", "perc": 0},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 16.1},
                        {"fuel": "wind", "perc": 11.9},
                    ],
                    "intensity": {"forecast": 284, "index": "very high"},
                    "regionid": 17,
                    "shortname": "Wales",
                },
                {
                    "dnoregion": "GB",
                    "generationmix": [
                        {"fuel": "biomass", "perc": 3.2},
                        {"fuel": "coal", "perc": 0},
                        {"fuel": "imports", "perc": 13.7},
                        {"fuel": "gas", "perc": 36.7},
                        {"fuel": "nuclear", "perc": 11.1},
                        {"fuel": "other", "perc": 0},
                        {"fuel": "hydro", "perc": 0},
                        {"fuel": "solar", "perc": 12.3},
                        {"fuel": "wind", "perc": 23},
                    ],
                    "intensity": {"forecast": 158, "index": "moderate"},
                    "regionid": 18,
                    "shortname": "GB",
                },
            ],
            "to": "2025-03-25T15:30Z",
        }
    ]
}
